site_name: Trial Embedded Drawio via MkDocs
site_description: MkDocsでのdrawio埋め込みのトライアル
site_author: Tomofumi Takayama
docs_dir: docs/src
site_dir: docs/site

theme:
  name: material
  navigation_depth: 3
  language: ja
  features:
    - navigation.instant
    - navigation.sections
    - navigation.expand
    - navigation.tabs
    - navigation.tracking
    - toc.integrate
    - search.highlight
    - search.suggest
    - navigation.indexes
    - content.code.copy
    - toc.follow

repo_name: trial-embedded-drawio-via-mkdocs
repo_url: https://github.com/your-username/trial-embedded-drawio-via-mkdocs

markdown_extensions:
  - attr_list
  - md_in_html
  - tables
  - footnotes
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - toc:
      permalink: true

plugins:
  - search:
      lang: ja
      separator: '[\s\-\.]+'
  - awesome-nav:
      filename: .nav.yml

